name: minigames
main: com.mhndk27.minigames.MiniGamesPlugin
version: 1.0
api-version: 1.20
depend: [WorldEdit]
softdepend: [PartySystem]
commands:
  minigame:
    description: Main command for minigames
permissions:
  minigames.use:
    description: Allows use of minigames commands
    default: true
