name: TeamsSystem
main: com.mhndk27.teamsys.TeamsSystem
version: 1.0
api-version: 1.20
commands:
  team:
    description: Manage teams - invite, leave, info
    usage: /<command> <invite|leave|info> [player]
permissions:
  teamsystem.use:
    description: Allows using team commands
    default: true
