name: TPM
main: com.mhndk27.tpm.TPMPlugin
version: 1.0.0
api-version: 1.20
commands:
  zstp:
    description: Execute teleport to waiting room command (Console only)
    usage: /zstp <player>
    permission: tpm.command.zstp
    permission-message: You don't have permission to execute this command.
    aliases: []
  lobbytp:
    description: Execute teleport to lobby command (Console only)
    usage: /lobbytp <player>
    permission: tpm.command.lobbytp
    permission-message: You don't have permission to execute this command.
permissions:
  tpm.command.zstp:
    description: Allows using the /zstp command from console only
    default: op
  tpm.command.lobbytp:
    description: Allows using the /lobbytp command from console only
    default: op
