name: minigames
version: 1.0
main: com.mhndk27.minigames.MiniGamesPlugin
api-version: 1.20
commands:
  minigame:
    description: Main minigame command
    usage: /<command>
  startgame:
    description: Start a minigame session
    usage: /startgame
