name: servercore
version: 1.0
main: com.mhndk27.servercore.Main
api-version: 1.20

commands:
  tpt:
    description: Teleport to minigame or lobby
    usage: /tpt <zombie_shooter|lobby>

permissions:
  servercore.zstp:
    default: op
  servercore.lobbytp:
    default: op
